development: &pgsql
  adapter: postgresql
  database: DB_NAME
  username: DB_USERNAME
  password: DB_PASSWD
  host: localhost
  port: 5432
  pool: 200 
  timeout: 5

production: &production
  <<: *pgsql
